# Generated by Django 6.0.2 on 2026-02-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('observaciones', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=True)),
                ('tema', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='estudiantes.estudiante')),
            ],
        ),
    ]
