# Generated by Django 6.0.2 on 2026-02-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['-fecha']},
        ),
    ]
